name: "On Push"

on:
  push:
    branches:
      - 'master'
    paths:
      - 'ops/**'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: push-${{github.repository}}-${{ github.branch }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: "Build and Push Docker Image"
    uses: webgrip/workflows/.github/workflows/docker-build-and-push.yml@main
    with:
      docker-context: ./ops/docker/native
      docker-file: Dockerfile
      docker-tags: |
        webgrip/github-action-runner:latest
        webgrip/github-action-runner:${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
